version: "2"
checks:
  file-lines:
    enabled: true
    config:
      threshold: 600
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 25
  identical-code:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 50
exclude_patterns:
  - "**/**/__tests__/"
  - "node_modules"
  - "conf"
  - "coverage"
  - "cypress"
  - "public"
  - "utility"

